---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: "17"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### New features and improvements ###
  - Handle playback skipping and fix progress sync (#128) @Shadowghost

  ### Bug Fixes ###
  - Add retry time to BadGateway response (#127) @crobibero
  - Handle playback skipping and fix progress sync (#128) @Shadowghost
