---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
version: "11.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.
category: "General"
artifacts:
- "Trakt.dll"
changelog: >
  changelog
