---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: "16"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### Bug Fixes ###
  - Retry episode scrobble without IDs if episode was not found by trakt (#102) @SenorSmartyPants
  - Fix episodes with IDs (#100) @SenorSmartyPants

  ### Code or Repo Maintenance ###
  - 10.8 support (#110) @crobibero
  - Use meta ci (#108) @crobibero

  ### CI & build changes ###
  - Use meta ci (#108) @crobibero
