---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: 19
targetAbi: "10.8.1.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### Bug Fixes ###
  - Fix unauthorized users not being skipped (#154) @Shadowghost
  - Fix MediaType metadata (#154) @Shadowghost
  - Don't fail tasks if one user fails (#154) @Shadowghost

  ### Features ###
  - Implement HDR metadata (#154) @Shadowghost
    - Implement metadata for episodes (#154) @Shadowghost
  - Switch to GUIDs (this requires reauthentication of all users) (#154) @Shadowghost
