---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: "15"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### New features and improvements ###
  - Handle TV show rewatches (#97) @dulli
  - Don't treat TVDB Id specially for episodes (#93) @SenorSmartyPants

  ### Code or Repo Maintenance ###
  - Use BaseItemKind (#98) @crobibero
  - Remove all warnings in project (#96) @crobibero
